name: flutter_microsoft_authentication
description: Flutter Wrapper for Microsoft Authentication Library to enable SSO across Android and iOS.
version: 0.2.0
homepage: https://github.com/BritehouseMobile/flutter-microsoft-authentication

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: za.co.britehouse.flutter_microsoft_authentication
    pluginClass: FlutterMicrosoftAuthenticationPlugin